Replace `zksync` crate with `zksync_web3_rs`
matter-labs/foundry-zksync pull request #110
Opened 2023-07-15 14:09 UTC by mpaulucci

## Motivation
`zksync` is a big crate with a lot of functionality that is irrelevant for foundry. That's why we are replacing the crate with the zksync SDK, which provides the same functionality that is needed for foundry but is much more lightweight.

Functionality that has been affected:
- zk_deposit
- zk_send
- zk_create

TODO items to be fully compatible with zksync functionality:
- Deposit and withdrawal of ERC20 tokens (work in progress),

2023-07-15 14:10 UTC, mpaulucci commented on cli/src/cmd/forge/zksolc_manager.rs
> -#[derive(Debug, Clone, Serialize)]
There was a compile error after removing `zksync` crate. Is this neeed?

2023-07-24 08:08 UTC, mm-zk approved these changes

2023-07-24 08:30 UTC, mm-zk requested changes
Seems that something didn't work (with signatures).

when I tried running against a local node:

```
../foundry-zksync/target/debug/zkforge zkc src/Greeter.sol:Greeter --constructor-args "ZkSync" --private-key 7726827caac94a7f9e1b160f7ea819f172f7b6f9d2a97f992c38edeab82d4110 --rpc-url http://localhost:8011  --chain 260
```

I get:

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ValidationFailed(General { msg: "Account validation returned invalid magic value. Most often this means that the signature is incorrect", data: [] })', src/node.rs:371:60

2023-08-03 15:57 UTC, mm-zk approved these changes

2023-08-03 15:57 UTC, merged