Adding support for forge test on zksync VM
matter-labs/foundry-zksync pull request #125
Opened 2023-10-13 13:09 UTC by mm-zk

With this PR, you can start running 'zkforge test' - which would compile and execute the tests using zksync in-memory node.

Currently these tests are NOT support any of the vm Hacks (like impersonation etc) - this will be added in future PRs.

2023-10-13 20:55 UTC, dutterbutter requested changes
@mm-zk I am hoping you can confirm my understanding but basically when we compile contracts (using zksolc), we first prepare the necessary inputs for the compiler. After compilation, we handle the output to extract and organize "artifacts", including the bytecode hash, factory dependencies, ABI, and bytecode . These artifacts are then stored in a mapping keyed by the contract name. 

**One question here:** What is the difference between `art.bytecode` and `art.deployed_bytecode` ? 

I see that we execute transactions via `run_era_transaction` from `era-revm`. Here we convert revm tx to era's `L2Tx`, execute that tx in era-test-node, update state of all the accounts touched, and return a revm `ResultAndState` with execution status and state changes which is then used to in revm to complete the process. 

This is where my confusion is. I have a disconnect where the artifacts created during compilation are used? I am assuming they are apart of either the db, or env passed to `run_era_transaction`?

2023-10-13 20:55 UTC, dutterbutter commented on Cargo.toml
> +#debug = 1
Nit: comment can be removed

2023-10-13 20:55 UTC, dutterbutter commented on Cargo.toml
> +# revm = { git = "https://github.com/bluealloy/revm/", branch = "release/v25" }
Nit: comment can be removed.

2023-10-13 20:55 UTC, dutterbutter commented on anvil/core/Cargo.toml
> +# revm = { version = "3", default-features = false, features = ["std", "serde", "memory_limit"] }
Same here.

2023-10-13 20:55 UTC, dutterbutter commented on chisel/Cargo.toml
> +# revm = "3"
Same here.

2023-10-13 20:55 UTC, dutterbutter commented on cli/Cargo.toml
> +#era_revm = { path = "../../revm_era"}
Same here.

2023-10-16 08:04 UTC, mm-zk commented
@dutterbutter
>One question here: What is the difference between art.bytecode and art.deployed_bytecode ?

In EVM - you have a bytecode that is generated by solidity - and then when deployed, it runs a 'constructor' to generate the 'deployed bytecode' that ends up in storage.

> This is where my confusion is. I have a disconnect where the artifacts created during compilation are used? I am assuming they are apart of either the db, or env passed to run_era_transaction?

Artifacts are 'serialized', and then foundry is passing them in tx.data, when creating contracts. See here: https://github.com/matter-labs/era-revm/blob/main/src/transactions.rs#L98

2023-10-16 13:52 UTC, dutterbutter approved these changes

2023-10-17 13:52 UTC, dutterbutter commented
Yeah @mm-zk looks like you hit a resource issue, based on the docs: "this means that the resources consumed in the process exceeded the limits"

```
2023-10-17T11:14:17.7806887Z ##[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
2023-10-17T11:14:17.7810605Z ##[error]Process completed with exit code 143.
```

2023-10-17 14:02 UTC, merged