fix: Return zero for blockhash in zk context
matter-labs/foundry-zksync pull request #400
Opened 2024-05-29 13:33 UTC by Jrigada

2024-05-29 22:20 UTC, nbaztec commented on crates/zksync/core/src/vm/tracer.rs
> +                self.farcall_handler.set_immediate_return(zero.to_vec());
```suggestion
                self.farcall_handler.set_immediate_return(rU256::ZERO.to_be_bytes_vec());
```

2024-05-29 22:20 UTC, nbaztec commented on zk-tests/src/Cheatcodes.t.sol
> +    }
This test can be part of `testZkPropagatedBlockEnv` in `Basic.t.sol` where the blocknumber can be hardcoded. We should check that the blockhash is zero both outside and within the zksync context.

2024-05-30 14:12 UTC, Karrq requested changes
When we looked at the era-contracts implementation there was a comment indicating that in EVM, a 0 is returned for blockhash when the block is older than 256. Could this mean that newer blocks will return a different hash?

Could you add a test that captures this behavior also? Using fork we can get a proper chain and retrieve the last block's hash using `block.number`

2024-05-30 17:23 UTC, nbaztec commented on crates/cheatcodes/src/inspector.rs
> +                //for each log in cloned logs call handle_expect_emit
```suggestion
                // for each log in cloned logs call handle_expect_emit
```

2024-05-30 19:02 UTC, Karrq requested changes

2024-05-30 19:02 UTC, Karrq commented on zk-tests/src/Cheatcodes.t.sol
> +contract Emitter {
Do these changes belong to this PR?

2024-05-30 20:49 UTC, Karrq approved these changes

2024-05-31 17:08 UTC, merged